name = "wallet-api"
main = "src/index.ts"
compatibility_date = "2022-11-07"

[[ d1_databases ]]
binding = "DB"
database_name = "wallet-database"
database_id = "6c950bd0-f350-4aa9-b90e-64e6bc233b87"
migrations_dir = "src/db/migrations"
